package net.mostlyoriginal.game.component;

/**
 * @author Daan van Yperen
 */
public enum ScriptCommand {
    LAVA_TENDRIL,
    LAVA_PRESSURE_UP,
    ANGRY_RANDOMIZE,
    DOLPHINIZE,
    ANGRY_NONE,
    HOLLOWEARTH,
    WATERWORLD,
    ADD_DUDES,
    KILL_DUDES,
    RESTART,
    CURE_FOR_DEATH,
    SPAWN_ICBMS,
    UNSPAWN_ICBMS,
    SPAWN_GALAXYBUCKS,
    SPAWN_ACCELERATOR,
    SPAWN_STRUCTURES,
    TRIGGER_EXPLOSIVES, WATER_PRESSURE_UP,ANGRY_ALL
}
